---
name: "Alexa Skill"
guid: "e62bf281-72af-4102-82a4-47649e856b81"
version: "1.0.0.0"
targetAbi: "10.11.6.0"
framework: "net6.0"
overview: "Alexa skill plugin for Jellyfin"
description: >
  This is a Jellyfin plugin for an Alexa skill to play media from your Jellyfin server.
  Besides, simple playback, other additional functions like playback of playlists or managing favorites are included.
category: "General"
owner: "NiceneNerd"
artifacts:
- "Jellyfin.Plugin.AlexaSkill.dll"
